---
- hosts: database 
  become: yes 
  tasks:
  - name: Install the new one 
    template: 
       src: ./server_list.j2
       dest: /etc/server_list.txt
       mode: '0600'
       setype: net_conf_t
